services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=80
      - DATABASE_URL=postgres://postgres:postgres@db:5432/laskuppen?sslmode=disable
      - GOOGLEAPI_KEY='AIzaSyCquG0FqE0hTgtcEOT-VeK6wzbJSdECi5E'
      - COOKIE_SECRET='o99AQxEwGdfavsz1c7yjkcQ6gTowOvHS'
    ports:
      - "5001:80"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laskuppen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
